version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm config set @bit:registry https://node.bit.dev
            - run: npm install
            - run: npm run testwithexit
            - run: ./node_modules/.bin/codecov
workflows:
    build-and-test:
      jobs:
        - build-and-test
